os:
  - osx
  - linux
env:
  - NANOMSG="git://github.com/nanomsg/nanomsg.git -b 0.3-beta"
  - NANOMSG="git://github.com/nanomsg/nanomsg.git -b 0.4-beta"
  - NANOMSG="git://github.com/nanomsg/nanomsg.git -b 0.5-beta"
  - NANOMSG="git://github.com/nanomsg/nanomsg.git"
before_install:
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm i 0.10 && nvm i 0.11 && nvm i 0.12 && nvm i iojs
  - echo -e "require('fs').writeFile('platform.sh','export PLATFORM=\"'+require('os').platform()+'\"')" >> "check.js"
  - node check && chmod a+x platform.sh && source platform.sh
  - git clone $NANOMSG
  - cd nanomsg && ./autogen.sh && ./configure && make
  - sudo make install
  - '[ "$PLATFORM" == "darwin" ] || sudo /sbin/ldconfig'
  - cd ..
branches:
  only:
    - master
language: c
script:
  - nvm use 0.10 && make && make check
  - nvm use 0.11 && make clean && make && make check
  - nvm use 0.12 && make clean && make && make check
  - nvm use iojs && make clean && make && make check
