os:
  - linux
env:
  - NODE_VERSION="0.10" NANOMSG="git://github.com/nanomsg/nanomsg.git -b 0.3-beta"
  - NODE_VERSION="0.11" NANOMSG="git://github.com/nanomsg/nanomsg.git -b 0.3-beta"
  - NODE_VERSION="iojs-v1.0.3" NANOMSG="git://github.com/nanomsg/nanomsg.git -b 0.3-beta"
  - NODE_VERSION="0.10" NANOMSG="git://github.com/nanomsg/nanomsg.git -b 0.4-beta"
  - NODE_VERSION="0.11" NANOMSG="git://github.com/nanomsg/nanomsg.git -b 0.4-beta"
  - NODE_VERSION="iojs-v1.0.3" NANOMSG="git://github.com/nanomsg/nanomsg.git -b 0.4-beta"
  - NODE_VERSION="0.10" NANOMSG="git://github.com/nanomsg/nanomsg.git -b 0.5-beta"
  - NODE_VERSION="0.11" NANOMSG="git://github.com/nanomsg/nanomsg.git -b 0.5-beta"
  - NODE_VERSION="iojs-v1.0.3" NANOMSG="git://github.com/nanomsg/nanomsg.git -b 0.5-beta"
  - NODE_VERSION="0.10" NANOMSG="git://github.com/nanomsg/nanomsg.git"
  - NODE_VERSION="0.11" NANOMSG="git://github.com/nanomsg/nanomsg.git"
  - NODE_VERSION="iojs-v1.0.3" NANOMSG="git://github.com/nanomsg/nanomsg.git"
before_install:
  - pwd
  - ls -la
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - node -v
  - git clone $NANOMSG
  - cd nanomsg && ./autogen.sh && ./configure && make
  - sudo make install && sudo /sbin/ldconfig
  - cd ..
branches:
  only:
    - master
language: c
script: make && make check
